// <auto-generated />
namespace computer_store_MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addDbSet : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addDbSet));
        
        string IMigrationMetadata.Id
        {
            get { return "202106131040163_addDbSet"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
